/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SatRouteImport } from './routes/sat'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IeltsRouteImport } from './routes/ielts'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CbtCentersRouteImport } from './routes/cbt-centers'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalConsultantRouteImport } from './routes/portal.consultant'
import { Route as PortalCentreRouteImport } from './routes/portal.centre'
import { Route as PortalAgentRouteImport } from './routes/portal.agent'
import { Route as CommunityThreadIdRouteImport } from './routes/community.$threadId'
import { Route as CbtSubjectIdRouteImport } from './routes/cbt.$subjectId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SatRoute = SatRouteImport.update({
  id: '/sat',
  path: '/sat',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IeltsRoute = IeltsRouteImport.update({
  id: '/ielts',
  path: '/ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CbtCentersRoute = CbtCentersRouteImport.update({
  id: '/cbt-centers',
  path: '/cbt-centers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalConsultantRoute = PortalConsultantRouteImport.update({
  id: '/consultant',
  path: '/consultant',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCentreRoute = PortalCentreRouteImport.update({
  id: '/centre',
  path: '/centre',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAgentRoute = PortalAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => PortalRoute,
} as any)
const CommunityThreadIdRoute = CommunityThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => CommunityRoute,
} as any)
const CbtSubjectIdRoute = CbtSubjectIdRouteImport.update({
  id: '/cbt/$subjectId',
  path: '/cbt/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/cbt-centers': typeof CbtCentersRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/ielts': typeof IeltsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sat': typeof SatRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/welcome': typeof WelcomeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cbt/$subjectId': typeof CbtSubjectIdRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/centre': typeof PortalCentreRoute
  '/portal/consultant': typeof PortalConsultantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/cbt-centers': typeof CbtCentersRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/ielts': typeof IeltsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sat': typeof SatRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/welcome': typeof WelcomeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cbt/$subjectId': typeof CbtSubjectIdRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/centre': typeof PortalCentreRoute
  '/portal/consultant': typeof PortalConsultantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/bookmarks': typeof BookmarksRoute
  '/cbt-centers': typeof CbtCentersRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exams': typeof ExamsRoute
  '/ielts': typeof IeltsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sat': typeof SatRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRoute
  '/welcome': typeof WelcomeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cbt/$subjectId': typeof CbtSubjectIdRoute
  '/community/$threadId': typeof CommunityThreadIdRoute
  '/portal/agent': typeof PortalAgentRoute
  '/portal/centre': typeof PortalCentreRoute
  '/portal/consultant': typeof PortalConsultantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/cbt-centers'
    | '/community'
    | '/dashboard'
    | '/exams'
    | '/ielts'
    | '/leaderboard'
    | '/login'
    | '/portal'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sat'
    | '/schools'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/welcome'
    | '/blog/$slug'
    | '/cbt/$subjectId'
    | '/community/$threadId'
    | '/portal/agent'
    | '/portal/centre'
    | '/portal/consultant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/cbt-centers'
    | '/community'
    | '/dashboard'
    | '/exams'
    | '/ielts'
    | '/leaderboard'
    | '/login'
    | '/portal'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sat'
    | '/schools'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/welcome'
    | '/blog/$slug'
    | '/cbt/$subjectId'
    | '/community/$threadId'
    | '/portal/agent'
    | '/portal/centre'
    | '/portal/consultant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/bookmarks'
    | '/cbt-centers'
    | '/community'
    | '/dashboard'
    | '/exams'
    | '/ielts'
    | '/leaderboard'
    | '/login'
    | '/portal'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/sat'
    | '/schools'
    | '/signup'
    | '/terms'
    | '/tools'
    | '/welcome'
    | '/blog/$slug'
    | '/cbt/$subjectId'
    | '/community/$threadId'
    | '/portal/agent'
    | '/portal/centre'
    | '/portal/consultant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookmarksRoute: typeof BookmarksRoute
  CbtCentersRoute: typeof CbtCentersRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExamsRoute: typeof ExamsRoute
  IeltsRoute: typeof IeltsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SatRoute: typeof SatRoute
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRoute
  WelcomeRoute: typeof WelcomeRoute
  CbtSubjectIdRoute: typeof CbtSubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sat': {
      id: '/sat'
      path: '/sat'
      fullPath: '/sat'
      preLoaderRoute: typeof SatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts': {
      id: '/ielts'
      path: '/ielts'
      fullPath: '/ielts'
      preLoaderRoute: typeof IeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbt-centers': {
      id: '/cbt-centers'
      path: '/cbt-centers'
      fullPath: '/cbt-centers'
      preLoaderRoute: typeof CbtCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/consultant': {
      id: '/portal/consultant'
      path: '/consultant'
      fullPath: '/portal/consultant'
      preLoaderRoute: typeof PortalConsultantRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/centre': {
      id: '/portal/centre'
      path: '/centre'
      fullPath: '/portal/centre'
      preLoaderRoute: typeof PortalCentreRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/agent': {
      id: '/portal/agent'
      path: '/agent'
      fullPath: '/portal/agent'
      preLoaderRoute: typeof PortalAgentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/community/$threadId': {
      id: '/community/$threadId'
      path: '/$threadId'
      fullPath: '/community/$threadId'
      preLoaderRoute: typeof CommunityThreadIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/cbt/$subjectId': {
      id: '/cbt/$subjectId'
      path: '/cbt/$subjectId'
      fullPath: '/cbt/$subjectId'
      preLoaderRoute: typeof CbtSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CommunityRouteChildren {
  CommunityThreadIdRoute: typeof CommunityThreadIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityThreadIdRoute: CommunityThreadIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface PortalRouteChildren {
  PortalAgentRoute: typeof PortalAgentRoute
  PortalCentreRoute: typeof PortalCentreRoute
  PortalConsultantRoute: typeof PortalConsultantRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAgentRoute: PortalAgentRoute,
  PortalCentreRoute: PortalCentreRoute,
  PortalConsultantRoute: PortalConsultantRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  BookmarksRoute: BookmarksRoute,
  CbtCentersRoute: CbtCentersRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExamsRoute: ExamsRoute,
  IeltsRoute: IeltsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SatRoute: SatRoute,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRoute,
  WelcomeRoute: WelcomeRoute,
  CbtSubjectIdRoute: CbtSubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
